version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: c1-northstar-db-dev
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: northstar
      POSTGRES_PASSWORD: northstar_password
      POSTGRES_DB: northstar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U northstar"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: